# Generated by Django 4.0.6 on 2022-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='detail',
            field=models.TextField(),
        ),
    ]
